// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/customer/GetByEmailApi/{email}": {
            "get": {
                "description": "分頁列表",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "CustomerApi"
                ],
                "summary": "根據Email獲取Customer",
                "parameters": [
                    {
                        "type": "string",
                        "description": "EMail",
                        "name": "email",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/base.Response"
                        }
                    }
                }
            }
        },
        "/customer/{id}": {
            "get": {
                "description": "根據Id獲取Customer對應的OutDto",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "CustomerApi"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id主鍵",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/base.Response"
                        }
                    }
                }
            }
        },
        "/customers": {
            "get": {
                "description": "Customer分頁列表",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "CustomerApi"
                ],
                "summary": "Customer分頁列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "第幾頁",
                        "name": "pageNum",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每頁大小",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "address",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "created",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "creator",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "email",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "industry",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "level",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "phone",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "region",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "remarks",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "source",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "updated",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/base.Response"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "登入並返回token+User",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "UserApi"
                ],
                "summary": "登入",
                "parameters": [
                    {
                        "description": "登入參數",
                        "name": "models.UserLoginReq",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UserLoginReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/base.Response"
                        }
                    }
                }
            }
        },
        "/menu/tree": {
            "get": {
                "description": "根據Token獲取使用者權限範圍功能樹",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "MenuApi"
                ],
                "summary": "獲取使用者權限範圍功能樹",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/base.Response"
                        }
                    }
                }
            }
        },
        "/product/GetByCodeApi/{code}": {
            "get": {
                "description": "根據Code獲取實體Product",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "ProductApi"
                ],
                "summary": "根據Code獲取Product",
                "parameters": [
                    {
                        "type": "string",
                        "description": "code",
                        "name": "code",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/base.Response"
                        }
                    }
                }
            }
        },
        "/product/{id}": {
            "get": {
                "description": "根據Id獲取Product對應的OutDto",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "ProductApi"
                ],
                "summary": "根據Id獲取Product對應的OutDto",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id主鍵",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/base.Response"
                        }
                    }
                }
            }
        },
        "/products": {
            "get": {
                "description": "Product分頁列表",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "ProductApi"
                ],
                "summary": "Product分頁列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "第幾頁",
                        "name": "pageNum",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每頁大小",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "code",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "created",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "creator",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "description",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Name        string  ` + "`" + `gorm:\"name\" form:\"name\" binding:\"required,oneof=运动鞋 洗衣液\"` + "`" + `",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "name": "price",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "unit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "updated",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/base.Response"
                        }
                    }
                }
            }
        },
        "/user/info": {
            "get": {
                "description": "根據Token獲取用戶信息",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "UserApi"
                ],
                "summary": "根據Token獲取用戶信息",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/base.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "base.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "models.UserLoginReq": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "token",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:5001",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "sh-Admin Api",
	Description:      "sh-Admin 後端接口",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
